#!/usr/bin/env python3
"""Wrap one GXP program in the raw2c object form used by Adrenaline."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    symbol = args.input.stem
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", symbol) is None:
        raise SystemExit(f"invalid C symbol derived from {args.input.name!r}")

    data = args.input.read_bytes()
    rows = []
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16])
        if offset + 16 < len(data):
            values += ","
        rows.append(f"\t{values}")

    source = (
        "/* Autogenerated from the verified GXP; do not edit. */\n\n"
        f"const unsigned char {symbol}[] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
        f"const int {symbol}_size = sizeof({symbol});\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
